"use client";

import { useState, useEffect } from "react";
import { useFirebase } from "@/lib/firebase";
import { ref, onValue } from "firebase/database";
import { TrendingUp, Target, ShieldAlert, ArrowRight } from "lucide-react";

interface TradingSignal {
  id: string;
  symbol: string;
  entry_price: number;
  stop_loss_price: number;
  take_profit_price: number;
  timestamp?: number;
}

export default function SignalsPage() {
  const { db, isConfigured } = useFirebase();
  const [signals, setSignals] = useState<TradingSignal[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!db || !isConfigured) {
      setLoading(false);
      return;
    }

    const sigRef = ref(db, "trading_signals");
    const unsubscribe = onValue(sigRef, (snapshot) => {
      const data = snapshot.val();
      if (data) {
        const sigList = Object.keys(data).map((key) => ({
          id: key,
          ...data[key],
        }));
        setSignals(sigList);
      } else {
        setSignals([]);
      }
      setLoading(false);
    });

    return () => unsubscribe();
  }, [db, isConfigured]);

  if (!isConfigured) {
    return (
      <div className="card">
        <h2>Please configure Firebase first to view trading signals.</h2>
      </div>
    );
  }

  return (
    <div className="animate-fade-in">
      <div className="page-header">
        <h1 className="page-title">Trading Signals</h1>
      </div>

      <div className="card mb-4" style={{ background: "linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(16, 185, 129, 0.1))" }}>
        <p style={{ display: "flex", alignItems: "center", gap: "0.5rem", fontWeight: 500 }}>
          <Target color="var(--primary)" /> 
          Signals are generated by the external engine. Connect to see live updates from your database.
        </p>
      </div>

      {loading ? (
        <div className="card">Loading signals...</div>
      ) : signals.length === 0 ? (
        <div className="card">
          <p style={{ color: "var(--text-secondary)", textAlign: "center", padding: "2rem 0" }}>
            No trading signals available in the database.
          </p>
        </div>
      ) : (
        <div className="grid-cols-3">
          {signals.map((signal) => {
            const risk = Math.abs(signal.entry_price - signal.stop_loss_price);
            const reward = Math.abs(signal.take_profit_price - signal.entry_price);
            const ratio = risk > 0 ? (reward / risk).toFixed(2) : "N/A";
            const isLong = signal.take_profit_price > signal.entry_price;

            return (
              <div key={signal.id} className="card glass-panel" style={{ display: "flex", flexDirection: "column" }}>
                <div className="flex-between mb-4">
                  <h3 style={{ fontSize: "1.5rem", fontWeight: 700, display: "flex", alignItems: "center", gap: "0.5rem" }}>
                    {signal.symbol}
                    {isLong ? (
                      <span className="badge badge-success">LONG</span>
                    ) : (
                      <span className="badge badge-danger">SHORT</span>
                    )}
                  </h3>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: "1rem", flex: 1 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.75rem", background: "rgba(99, 102, 241, 0.05)", borderRadius: "var(--radius-sm)" }}>
                    <span style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>Entry Price</span>
                    <span style={{ fontWeight: 600, fontSize: "1.125rem" }}>${Number(signal.entry_price).toFixed(2)}</span>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.75rem", background: "rgba(16, 185, 129, 0.05)", borderRadius: "var(--radius-sm)" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--success)" }}>
                      <TrendingUp size={16} />
                      <span style={{ fontSize: "0.875rem" }}>Take Profit</span>
                    </div>
                    <span style={{ fontWeight: 600 }}>${Number(signal.take_profit_price).toFixed(2)}</span>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.75rem", background: "rgba(239, 68, 68, 0.05)", borderRadius: "var(--radius-sm)" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--danger)" }}>
                      <ShieldAlert size={16} />
                      <span style={{ fontSize: "0.875rem" }}>Stop Loss</span>
                    </div>
                    <span style={{ fontWeight: 600 }}>${Number(signal.stop_loss_price).toFixed(2)}</span>
                  </div>
                </div>

                <div className="mt-4" style={{ paddingTop: "1rem", borderTop: "1px solid var(--surface-border)", display: "flex", justifyContent: "space-between", fontSize: "0.875rem" }}>
                  <span style={{ color: "var(--text-secondary)" }}>Risk/Reward Ratio</span>
                  <span style={{ fontWeight: 600 }}>1 : {ratio}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
